"""
Regenerates the demo assets from real artifacts. Run by the maintainer, NOT
needed by someone who only wants to try the demo (the outputs are committed).

    CHROMA_PERSIST_DIR=<full index> python -m demo.build_demo_assets

Inputs : the full local corpus + full Chroma index + agent traces written by
         real runs of the agent (logs/traces/*.json).
Outputs: demo/prerecorded_responses.json  -- real LLM reports from those runs,
                                             with the exact retrieved excerpts
         demo/sample_corpus.jsonl         -- the public-record documents those
                                             responses cite, plus a few more

The retrieval for each recorded query is re-run and compared with the trace;
if the document order differs the script aborts, so a recorded report is never
paired with evidence it was not generated from.
"""
import json
import re
from pathlib import Path

from agent.graph import build_sources, extract_cited_indices, make_chroma_retriever
from config import DEMO_DIR, Settings
from vectorstore.corpus import load_corpus

# Extra documents so the sample corpus can exercise OFAC / CourtListener
# retrieval and the demo golden set (all appear in eval/golden_set.json).
EXTRA_DOC_IDS = [
    "ofac-sdn-26651", "ofac-sdn-28389", "ofac-sdn-25552", "ofac-sdn-23738",
    "ofac-sdn-53890", "ofac-sdn-51572",
    "courtlistener-9481353", "courtlistener-4872437", "courtlistener-10965051",
    "sec-edgar-0001312109-22-000051:si-20211231.htm",
]
NOTICE = (
    "PRERECORDED RESPONSE: this report was generated by a real run of the agent "
    "(retrieval + LLM) on 2026-09-18 and saved. It is replayed unchanged; it was "
    "not generated for your request."
)
TEXT_FALLBACK_CHARS = 8000


def filing_url(doc: dict) -> str:
    """Existing corpus SEC docs link to the company page; derive the filing URL."""
    if doc["source"] != "SEC_EDGAR":
        return doc["url"]
    m = re.search(r"CIK=(\d+)", doc["url"])
    adsh, _, filename = doc["doc_id"].removeprefix("sec-edgar-").partition(":")
    if not m or not filename:
        return doc["url"]
    return f"https://www.sec.gov/Archives/edgar/data/{m.group(1).lstrip('0')}/{adsh.replace('-', '')}/{filename}"


def main() -> None:
    settings = Settings.from_env()
    corpus = {d["doc_id"]: d for d in load_corpus(settings.corpus_path)}
    retrieve = make_chroma_retriever(settings)

    traces = [json.loads(f.read_text()) for f in sorted(settings.trace_dir.glob("trace_*.json"))]
    latest: dict[str, dict] = {}
    for t in traces:  # sorted by time, so the last one per query wins
        latest[t["entity_profile"]] = t

    responses, needed_text_len = [], {}
    for query, t in latest.items():
        chunks = retrieve(query, settings.top_k)
        traced_ids = [c["doc_id"] for c in t["step_1_retrieval"]["chunks"]]
        if [c["doc_id"] for c in chunks] != traced_ids:
            raise SystemExit(f"Retrieval for {query!r} no longer matches its trace "
                             f"({traced_ids} vs {[c['doc_id'] for c in chunks]}); refusing to pair "
                             "a recorded report with different evidence.")
        report = t["step_3_final_report"]
        cited = extract_cited_indices(report, len(chunks))
        sources = build_sources(chunks, cited)
        for s_, c in zip(sources, chunks):
            s_["url"] = filing_url(corpus[c["doc_id"]])
            full = corpus[c["doc_id"]]["text"]
            pos = full.find(c["text"])
            needed_text_len[c["doc_id"]] = max(
                needed_text_len.get(c["doc_id"], 0),
                pos + len(c["text"]) if pos >= 0 else TEXT_FALLBACK_CHARS)
        citations = []
        for i in cited:
            if chunks[i - 1]["doc_id"] not in citations:
                citations.append(chunks[i - 1]["doc_id"])
        responses.append({
            "query": query, "report": report, "citations": citations, "sources": sources,
            "token_usage": t["token_usage"], "recorded_at": t["timestamp"][:8],
        })

    out = {"notice": NOTICE, "model": settings.llm_model, "responses": responses}
    (DEMO_DIR / "prerecorded_responses.json").write_text(json.dumps(out, indent=2, ensure_ascii=False))

    ids = list(dict.fromkeys(list(needed_text_len) + EXTRA_DOC_IDS))
    with open(DEMO_DIR / "sample_corpus.jsonl", "w", encoding="utf-8") as f:
        for doc_id in ids:
            d = corpus[doc_id]
            keep = max(needed_text_len.get(doc_id, 0), 3000 if d["source"] == "SEC_EDGAR" else 0)
            f.write(json.dumps({
                "doc_id": d["doc_id"], "source": d["source"], "entity_type": d["entity_type"],
                "title": d["title"], "url": filing_url(d),
                "text": d["text"][:keep] if keep else d["text"],
                "retrieved_at": d["retrieved_at"],
            }, ensure_ascii=False) + "\n")
    print(f"{len(responses)} prerecorded responses; {len(ids)} sample-corpus docs")


if __name__ == "__main__":
    main()
